services:
  accounts:
    image: "navs07/accounts:v1"
    container_name: "accounts-service"
    ports:
      - "8080:8080"
#      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - accounts-network
  cards:
    image: "navs07/cards:v1"
    container_name: "cards-service"
    ports:
      - "8081:8081"
#      - "8091:8091"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - cards-network
  loans:
    image: "navs07/loans:v1"
    container_name: "loans-service"
    ports:
      - "8082:8082"
#      - "8092:8092"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - loans-network
networks:
  accounts-network:
    driver: bridge
  cards-network:
    driver: bridge
  loans-network:
    driver: bridge