build:
  version: "3.0.0"

spring:
  config:
    activate:
      on-profile: "dev"

loans:
  message: "Welcome to Nexus Bank loans service"
  contactDetails:
    name: "Naveen - Developer"
    email: "naveen@gmail.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345