build:
  version: "1.0.0"

spring:
  config:
    activate:
      on-profile: "prod"

loans:
  message: "Welcome to Nexus Bank loans service"
  contactDetails:
    name: "Harsha - Technical Lead"
    email: "harsha@gmail.com"
  onCallSupport:
    - (777) 555-1234
    - (777) 523-1345