services:
  configserver:
    image: "navs07/configserver:v3"
    container_name: "config-server"
    ports:
      - "8888:8888"
    healthcheck:
      test: "curl --fail --silent localhost:8888/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yaml
      service: microservice-base-config

  eurekaserver:
    image: "navs07/eurekaserver:v1"
    container_name: "eureka-server"
    ports:
      - "8070:8070"
    depends_on:
      configserver:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yaml
      service: microservice-configserver-config
    environment:
      SPRING_APPLICATION_NAME: eurekaserver

  accounts:
    image: "navs07/accounts:v3"
    container_name: "accounts-service"
    ports:
      - "8080:8080"
    #      - "8090:8090"
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: accounts-service
    extends:
      file: common-config.yaml
      service: microservice-eurekaserver-config

  cards:
    image: "navs07/cards:v3"
    container_name: "cards-service"
    ports:
      - "8081:8081"
    #      - "8091:8091"
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: cards-service
    extends:
      file: common-config.yaml
      service: microservice-eurekaserver-config

  loans:
    image: "navs07/loans:v3"
    container_name: "loans-service"
    ports:
      - "8082:8082"
    #      - "8092:8092"
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: loans-service
    extends:
      file: common-config.yaml
      service: microservice-eurekaserver-config

networks:
  nexusbank-network:
    driver: bridge